# Generated by Django 5.2.1 on 2025-05-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zure_app', '0002_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
