# Generated by Django 5.2.1 on 2025-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zure_app', '0003_alter_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='informativo',
            field=models.TextField(null=True),
        ),
    ]
