# Generated by Django 5.2.1 on 2025-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zure_app', '0004_produto_informativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='beneficios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='modo_de_uso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='titulo_informativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
